### PR TITLE
fix: added .js to all file import/exports

### PR DESCRIPTION
**Pull request by adamhwang**
To address ESM module resolution needs: https://github.com/react-financial/react-financial-charts/issues/606

#### Checklist
- [x] My commits follow [Conventional Commits](https://www.conventionalcommits.org)
- [ ] documentation is updated

### CODE REVIEW

**Comment by adamhwang** [comment]
I've confirmed this is a comprehensive changeset with `eslint-plugin-import`. I cannot check-in the eslint rules without rebuilding the package-lock as its an older version than I have available.

If you're interested in confirming / adding, the package is `eslint-plugin-import` with the following additions to `.eslintrc.yaml`:
```
extends:
  - "plugin:import/warnings"
  - "plugin:import/typescript"
rules:
  "import/extensions":
    - 2
    - "always"
```

**Review by OnufryKlaczynski — APPROVED** [review]
LGTM

**Comment by adamhwang** [comment]
> It currently does not build, and needs a rebase to fix conflicts. I'm tempted to revert the package.json flag instead.

I rebased and added the lint rule, but unfortunately appear to be running into this jest issue with the test: https://github.com/kulshekhar/ts-jest/issues/1057

**Comment by mattiaz9** [comment]
this library has been broken for months because of this. Please @markmcdowell release a new version 🙏

**Comment by LukeKoz** [comment]
Is there any other workaround in the meantime?

**Comment by hakunin** [comment]
I can't use the library because of this, please add a maintainer if renaming a few files is too overwhelming.

**Comment by markmcdowell** [comment]
Resolved in #676

**Pull request closed without merging**
